### ISSUE TITLE
Referencing Markdown Map from DITA Map broken

### ISSUE THREAD

**Issue by raducoravu** [jelovirt/org.lwdita#201]
Based on this syntax:
https://github.com/jelovirt/org.lwdita/wiki/Markdown-DITA-syntax#markdown-dita-map-syntax

So I have this test.mditamap DITA Map:

    ---
    $schema: urn:oasis:names:tc:dita:xsd:map.xsd
    ---
    # Map title
    
    - [Topic title](abc.md)

and if I publish it directly it works.
But if I refer to it in a regular DITA Map:

      <topicref href="test.mditamap" format="mditamap"/>

when I publish I get this publishing warning and the submap is not expanded in place:

         [xslt] .../dita/flowers/flowers.ditamap:14:47: [DOTX009W][WARN]: Could not retrieve a title from 'test.mditamap'. Using 'test.mditamap' instead.

**Comment by pxquim** [comment]
I would like to argue for what I believe could be a more seamless authoring experience in Markdown: good configurable defaults that would avoid the need for Markdown authors to care about `$schema` in common scenarios.

- Within DITA, the `format="..."` might implicitly define a default schema, overridable with `$schema`. For example, `format="mditamap"` would interpret the Markdown file as a map, unless `$schema` said otherwise.
- Within Markdown, the file extension might implicitly define a default schema, like `format="..."` would. For example, `map.mditamap` would interpret the Markdown file as a map, unless `$schema` said otherwise. And perhaps we might have `do.mdtask` be interpreted as a DITA task in Markdown.

**Comment by markgif** [comment]
FYI - on an MDITA (Markdown Lightweight DITA) map - I'm on the Lightweight DITA Subcommittee and we have been discussing using YAML for an MDITA map instead of the existing Markdown-based map. There has not been much implementation of the Markdown-based map, and YAML is attractive, being structured by nature. But we have not decided yet and we may not have time to add it before the first LwDITA spec is released.

Any feedback on this is very welcome.

**Comment by pxquim** [comment]
DITA XML maps enable seamless publication of a mix of XML DITA and MDITA files, and I am already taking advantage of that.

But I want to enable casual authors (developers) to contribute larger pockets of Markdown documentation, including maps. The MDITA map will be natural for these authors, and it is similar to what other pure Markdown tools do.

The XML DITA map will be seen as alien in this context. In fact, even the YAML property `$schema: urn:oasis:names:tc:dita:xsd:map.xsd` will be seen as alien, but I hope good defaults (like a mditamap extension) will make the schema optional in the common scenarios.

YAML maps would also work, but YAML can be an unforgiving format for authors. I would not give up on the MDITA map.

**Comment by jelovirt** [comment]
The problem here is actually DITA-OT itself. Fixed by https://github.com/dita-ot/dita-ot/pull/4353
