### ISSUE TITLE
Backslash Escapes not working in Markdown input

### ISSUE THREAD

**Issue by chegedita** [jelovirt/org.lwdita#49]
https://github.com/dita-ot/dita-ot/issues/3267#issue-425335348

**Comment by ritti** [comment]
The issue seems not to be fixed. It still exists with DITA-OT 3.4 where lwdita 2.3.2 is in place. Can you please reopen the issue?

Attached is the source dita-xml file and the resulting markdown file when transformed via command
`dita-ot-3.4\bin\dita" --input=Test.ditamap --output=out\markdown --format=markdown_github`

![2019-11-21 06_44_13-Window](https://user-images.githubusercontent.com/14054526/69307318-7c318000-0c2a-11ea-88e4-6ccfe287274c.png)

**Comment by ritti** [comment]
Please ignore, New issue created #61
